@startuml
title C4 Class Diagram: Externe services die niet beschikbaar zijn

'hide circle
'skinparam linetype ortho

top to bottom direction

package "controller" {
    class FlightsController {
        getFlightPrice(origin: String, destination: String, departureDate: Date, returnDate: Date)
    }
}

package "service" {
    interface FlightsService {
        getFlightPrice(origin: String, destination: String, departureDate: Date, returnDate: Date): double
    }

    class FlightsServiceImpl {
        getFlightPrice(origin: String, destination: String, departureDate: Date, returnDate: Date): double
    }
}

package "api" {
    interface ExternalAPIHandler {
        call(endpoint: Endpoint): Optional<JSONObject>
    }

    class ExternalAPIHandlerImpl {
        MAX_RETRIES: int
        RETRY_DELAY: Duration
        call(endpoint: Endpoint): Optional<JSONObject>
        getCachedResponse(endpoint: Endpoint): Optional<JSONObject>
        cacheResponse(endpoint: Endpoint, response: JSONObject): void
    }

    class Endpoint {
        url: String
        queryParams: HashMap<String, String>
        bodyHash: String
    }

    enum Method {
        GET, POST, PUT, DELETE
    }
}

package "repository" {
    interface CacheRepository {
        save(key: Endpoint, response: JSONObject, duration: Duration): void
        get(key: Endpoint): Optional<JSONObject>
    }

    class RedisCacheRepository {
        save(key: Endpoint, response: JSONObject, duration: Duration): void
        get(key: Endpoint): Optional<JSONObject>
        generateKey(endpoint: Endpoint): String
    }
}

FlightsController --> "flightService 1" FlightsService
FlightsServiceImpl .u.|> FlightsService
FlightsServiceImpl --> "externalAPIHandler 1" ExternalAPIHandler
ExternalAPIHandlerImpl .u.|> ExternalAPIHandler
ExternalAPIHandlerImpl -r-> "cacheRepository 1" CacheRepository
RedisCacheRepository .u.|> CacheRepository
ExternalAPIHandlerImpl ..> "endpoint 1" Endpoint
Endpoint ..> "method 1" Method

@enduml
