@startuml
title C4 Class Diagram - Booking


package "backend" {

interface IBookingAdapter {
    + getBookings(): List<Booking>
    + makeBooking(booking: Booking)
}

class BookingComAdapter {
    + getBookings(): List<Booking>
    + makeBooking(booking: Booking)
}

class TripAdvisorAdapter {
    + getBookings(): List<Booking>
    + makeBooking(booking: Booking)
}

class EigenBeheerHandler {
    + getBookings(): List<Booking>
    + makeBooking(booking: Booking)
}

class BookingController {
    + getBookings(): List<Booking>
    + makeBooking(booking: Booking)
}

class BookingService {
    + getBookings(): List<Booking>
    + makeBooking(booking: Booking)
}

}

IBookingAdapter <|.. BookingComAdapter
IBookingAdapter <|.. TripAdvisorAdapter
IBookingAdapter <|.. EigenBeheerHandler
BookingComAdapter --> "bookingComAPI 1" "BookingCom API"
TripAdvisorAdapter --> "tripAdvisorAPI 1" "TripAdvisor API"

BookingController --> "bookingService 1" BookingService
BookingService --> "iBookingAdapter 1" IBookingAdapter
@enduml