@startuml
title C4 Class Diagram: Verschillende boekingsservices integreren


package "backend" {

interface IBookingAdapter {
    + getBookings(): List<Booking>
    + makeBooking(booking: Booking)
}

class BookingComAdapter {
    + getBookings(): List<Booking>
    + makeBooking(booking: Booking)
}

class TripadvisorAdapter {
    + getBookings(): List<Booking>
    + makeBooking(booking: Booking)
}

class EigenBeheerHandler {
    + getBookings(): List<Booking>
    + makeBooking(booking: Booking)
}

class BookingController {
    + getBookings(): List<Booking>
    + makeBooking(booking: Booking)
}

class BookingService {
    + getBookings(): List<Booking>
    + makeBooking(booking: Booking)
}

}

IBookingAdapter <|.. BookingComAdapter
IBookingAdapter <|.. TripadvisorAdapter
IBookingAdapter <|.. EigenBeheerHandler
BookingComAdapter --> "bookingComAPI 1" "Booking.com API"
TripadvisorAdapter --> "tripAdvisorAPI 1" "Tripadvisor API"

BookingController --> "bookingService 1" BookingService
BookingService --> "iBookingAdapter 1" IBookingAdapter
@enduml
