@startuml
title C4 Component diagram: Verschillende boekingsservices integreren
!include <C4/C4_Component.puml>
top to bottom direction


Container(Frontend, "Frontend", "Javascript en React", "Toont de UI voor het planproces van de reiziger en het ticketsysteem van de reisagent.")


Container_Boundary(backend, "Backend") {
Component(bookingController, "BookingController", "Spring Boot Controller", "Verwerkt requests van de frontend en geeft door aan de juiste service")
Component(bookingService, "BookingService", "Spring Boot Service", "Verwerkt resultaten van booking services en zet om naar domeinobjecten")
Component(BookingComAdapter, "BookingComAdapter", "Spring Boot Component", "Adapter voor Booking.com API")
Component(tripAdvisorAdapter, "TripadvisorAdapter", "Spring Boot Component", "Adapter voor Tripadvisor API")
}
System_Ext(bookingComApi, "Booking.com API", "API van Booking.com")
System_Ext(tripAdvisorApi, "Tripadvisor API", "API van Tripadvisor")

Rel(Frontend, bookingController, "plant reizen en stemt af via", "JSON/REST")
Rel(bookingController, bookingService, "verwerkt boekingen via")
Rel(bookingService, BookingComAdapter, "roept booking service aan via")
Rel(bookingService, tripAdvisorAdapter, "roept booking service aan via")
Rel(BookingComAdapter, bookingComApi, "calls", "JSON/REST")
Rel(tripAdvisorAdapter, tripAdvisorApi, "calls", "JSON/REST")


SHOW_FLOATING_LEGEND()

@enduml
