@startuml
title C4 Dynamisch container diagram: een reis boeken op Triptop
!include <C4/C4_Container.puml>

top to bottom direction

SHOW_PERSON_OUTLINE()

System_Boundary(system, "Triptop") {
    Container(frontend, "Frontend", "Javascript en React", "Toont de UI voor het planproces van de reiziger en het ticketsysteem van de reisagent.")
    Container(backend, "Backend", "Java en Spring Boot", "Verzorgt de logica van het systeem, en verwerkt alle reisdata")
    ContainerDb(db, "Database", "Microsoft SQL Server", "Slaat alle informatie over een reis op")
    Container(cache, "Cache", "Redis", "Slaat API-responses op om api calls te verminderen")
}

System_Ext(booking, "Booking.com API", "Biedt hotels, vluchten, autoverhuur, taxi's en attracties")
System_Ext(tripadvisor, "Tripadvisor API", "Biedt restaurants, hotels, vluchten, cruises en autoverhuur aan")
System_Ext(mollie, "Mollie", "Betalingsysteem voor het betalen via iDEAL, creditcard en paypal")

' BOOKING A TRIP
Rel_D(frontend, backend, "1: verstuurt algemene gegevens (bestemming, vertrekdatum+locatie, einddatum+locatie)", "JSON/REST")

Rel(backend, booking, "2a: vraagt gegevens op op basis van de algemene gegevens", "JSON/REST")
Rel(backend, tripadvisor, "2b: vraagt gegevens op op basis van de algemene gegevens", "JSON/REST")

Rel(booking, backend, "3a: verstuurt data terug over hotels, vluchten, autoverhuur, taxi's en attracties", "JSON/REST")
Rel(tripadvisor, backend, "3b: verstuurt data terug over restaurants, hotels, vluchten, cruises en autoverhuur", "JSON/REST")

Rel_L(backend, cache, "4: slaat API-responses op in", "Jedis")

Rel_U(backend, frontend, "5: toont opties van de externe systemen aan gebruiker", "JSON/REST")

Rel_D(frontend, backend, "6: verstuurt keuze van gebruiker", "JSON/REST")

Rel_R(backend, db, "7: slaat keuze van de gebruiker op", "SQL/JdbcTemplate")

Rel(backend, booking, "8a: boekt de gekozen reisopties van de gebruiker", "JSON/REST")
Rel(backend, tripadvisor, "8b: boekt de gekozen reisopties van de gebruiker", "JSON/REST")

Rel(booking, backend, "9a: verstuurt een confirmatie voor de boeking", "JSON/REST")
Rel(tripadvisor, backend, "9b: verstuurt een confirmatie voor de boeking", "JSON/REST")

Rel_U(backend, frontend, "10: verstuurt confirmatie over de boeking en hoeveel het gaat kosten", "JSON/REST")

Rel_D(frontend, backend, "11: geeft aan te willen betalen", "JSON/REST")
Rel(backend, mollie, "12: verstuurt betaalverzoek door", "?/REST")

SHOW_FLOATING_LEGEND()

@enduml
