@startuml
!include <C4/C4_Component.puml>
title Component diagram

LAYOUT_TOP_DOWN()
SHOW_PERSON_OUTLINE()

Container(frontend, "Frontend", "Javascript en React", "Toont de UI voor het planproces van de reiziger en het ticketsysteem van de reisagent")

Container_Boundary(backend, "Backend") {
    Component(controller, "Generieke controller", "Spring Boot RestController", "Verwerkt requests van de frontend en geeft door aan de juiste service")
    Component(service, "Generieke service", "Spring Boot Service", "Verwerkt resultaten van externe services en zet om naar domeinobjecten")
    Component(strategy, "Generieke strategy", "Spring Boot Component", "Dynamisch toepassen van verschillende strategieën op basis van context en criteria")
    Component(apiHandler, "ExternalAPIHandler", "Spring Boot Component", "Aanroepen van externe services en afhandelen van fouten en retries")
}

System_Ext(api, "Externe API", "API van externe service")

Rel(frontend, controller, "maakt API verzoeken voor generieke data naar", "JSON/REST")
Rel(controller, service, "stuurt request door om af te handelen naar", "Method call")
Rel(service, strategy, "past functionaliteit aan op een strategy via", "Method call")
Rel(strategy, apiHandler, "roept externe service aan via", "Method call")
Rel(apiHandler, api, "maakt API verzoeken voor generieke data naar", "JSON/REST")

SHOW_FLOATING_LEGEND()
@enduml

